[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[program:api_v1]
command=/app/venv/bin/python -m uvicorn web_api.main:app --host 0.0.0.0 --port 5001 --workers %(ENV_API_WORKERS)s --timeout-keep-alive 15
directory=/app
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=60
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
